### ISSUE TITLE
stack: add kakarot+madara swap+starkshet to starknet stack

### ISSUE THREAD

**Issue by d-roak** [keep-starknet-strange/madara-infra#7]
Add it to the compose file

ref: #4

**Comment by ftupas** [comment]
Hello there, may I take this?

**Comment by d-roak** [comment]
Actually, we can do this better. Synchronize with @ClementWalter, for us to have independent Dockerfiles for each one of those applications and build images for their repos registry!

Do you want to take it?

**Comment by ftupas** [comment]
Gotcha, we can split the applications and have their own images 👍 Yes kindly assign it to me, thanks!

**Comment by d-roak** [comment]
Assigned! The images should be committed in the official repos, then added here in our global `docker-compose.yml`

**Comment by ClementWalter** [comment]
@ftupas yes you can do this.

So the idea is to add
- the [kakacet](https://github.com/kkrt-labs/kakacet) images (I've added them in the build). Since we've just forked starknet, you may want to update the fork to make the `kakarot.compute_starknet_address` call in the frontend and share the backend. It's also possible that you need to parametrize a bit differently not to conflict with the ports used by starkcet
- the [kakarot-rpc](https://github.com/kkrt-labs/kakarot-rpc/pkgs/container/kakarot-rpc%2Fnode) docker image.

The deployed kakarot address can be found from the `misc-apps` run, we need to add a `volume` to be able to read from the `/app/kakarot/deployments/sharingan/deployments.json`

I'm going to build the starksheet front end docker image elsewhere.

**Comment by d-roak** [comment]
fixed at #16
